web/logs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.decorators import specialist_required
from logs.views import (
    AnomalousEventDeleteView,
    AnomalousEventListView,
    GenerateTestAnomalousEventView,
    LogFileAddView,
    LogFileDeleteView,
    LogFileEditView,
    LogFileListView,
    LogTypeAddView,
    LogTypeDeleteView,
    LogTypeEditView,
    LogTypeListView,
    MainPageView,
    OneTimeScanAddView,
    OneTimeScanAnomalousEventListView,
    OneTimeScanDeleteView,
    OneTimeScanListView,
    SearchPatternAddView,
    SearchPatternDeleteView,
    SearchPatternEditView,
    SearchPatternListView,
)


app_name = "logs"

urlpatterns = [
    path(
        "anomalous-events/",
        login_required(AnomalousEventListView.as_view()),
        name="anomalous_events_list",
    ),
    path(
        "anomalous-events/<int:anomalous_event_id>/delete",
        specialist_required(AnomalousEventDeleteView.as_view()),
        name="anomalous_event_delete",
    ),
    path(
        "log-files/", login_required(LogFileListView.as_view()), name="log_files_list"
    ),
    path(
        "log-files/add/",
        specialist_required(LogFileAddView.as_view()),
        name="log_file_add",
    ),
    path(
        "log-files/<int:log_file_id>/edit/",
        specialist_required(LogFileEditView.as_view()),
        name="log_file_edit",
    ),
    path(
        "log-files/<int:log_file_id>/delete/",
        specialist_required(LogFileDeleteView.as_view()),
        name="log_file_delete",
    ),
    path(
        "log-types/", login_required(LogTypeListView.as_view()), name="log_types_list"
    ),
    path(
        "log-types/add/",
        specialist_required(LogTypeAddView.as_view()),
        name="log_type_add",
    ),
    path(
        "log-types/<int:log_type_id>/edit/",
        specialist_required(LogTypeEditView.as_view()),
        name="log_type_edit",
    ),
    path(
        "log-types/<int:log_type_id>/delete/",
        specialist_required(LogTypeDeleteView.as_view()),
        name="log_type_delete",
    ),
    path(
        "search-patterns/",
        login_required(SearchPatternListView.as_view()),
        name="search_patterns_list",
    ),
    path(
        "search-patterns/add/",
        specialist_required(SearchPatternAddView.as_view()),
        name="search_pattern_add",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/edit/",
        specialist_required(SearchPatternEditView.as_view()),
        name="search_pattern_edit",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/delete/",
        specialist_required(SearchPatternDeleteView.as_view()),
        name="search_pattern_delete",
    ),
    path(
        "one-time-scans/",
        login_required(OneTimeScanListView.as_view()),
        name="one_time_scans_list",
    ),
    path(
        "one-time-scans/add/",
        specialist_required(OneTimeScanAddView.as_view()),
        name="one_time_scan_add",
    ),
    path(
        "one-time-scans/<int:log_file_id>/delete/",
        specialist_required(OneTimeScanDeleteView.as_view()),
        name="one_time_scan_delete",
    ),
    path(
        "one-time-scans/<int:log_file_id>/anomalous-events/",
        login_required(OneTimeScanAnomalousEventListView.as_view()),
        name="one_time_scan_anomalous_events_list",
    ),
    path(
        "generate-test-anomalous-event/",
        login_required(GenerateTestAnomalousEventView.as_view()),
        name="generate_test_anomalous_event",
    ),
    path("", login_required(MainPageView.as_view()), name="main_page"),
]

web/main/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path("users/", include("users.urls")),
    path("logs/", include("logs.urls")),
    path("", RedirectView.as_view(url="logs/")),
]

web/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from core.decorators import admin_required
from users.forms import LoginForm
from users.views import UserAddView, UserDeleteView, UserEditView, UserListView


app_name = "users"

urlpatterns = [
    path(
        "logout/",
        login_required(LogoutView.as_view(template_name="users/logout.html")),
        name="user_logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html", form_class=LoginForm),
        name="user_login",
    ),
    path("add/", admin_required(UserAddView.as_view()), name="user_add"),
    path(
        "<int:user_id>/edit/", admin_required(UserEditView.as_view()), name="user_edit"
    ),
    path(
        "<int:user_id>/delete/",
        admin_required(UserDeleteView.as_view()),
        name="user_delete",
    ),
    path("", admin_required(UserListView.as_view()), name="users_list"),
]

web/templates/includes/anchor_finder.html
<script>
    var anchorId = window.location.hash.substring(1);
    var element = document.getElementById(anchorId);
    var counter = 0;
    if (element) {
        var isChange = true;
        function toggleBackgroundColor() {
            if (counter == 6) {
                return
            }
            if (isChange) {
                element.classList.add('table-danger');
            } else {
                element.classList.remove('table-danger');
            }
            isChange = !isChange;
            counter++;
        }
        setInterval(toggleBackgroundColor, 500);
    }
</script>

web/templates/includes/header.html
<div class="container-fluid text-center py-2">
    <div class="d-flex justify-content-between">
        <div class="col-6 d-flex flex-row justify-content-start">
            {% if request.user.is_authenticated %}
                <a class="col-0.5 btn btn-outline-light mx-1" href="{% url 'logs:main_page' %}">«</i></a>
                <a class="col-3 btn btn-outline-light mx-1" href="{% url 'logs:anomalous_events_list' %}">Аномальные события</a>
                <a class="col-2 btn btn-outline-light mx-1" href="{% url 'logs:log_files_list' %}">Лог-файлы</a>
                <a class="col-3 btn btn-outline-light mx-1" href="{% url 'logs:log_types_list' %}">Типы протоколов / ПО</a>
                <a class="col-3 btn btn-outline-light mx-1" href="{% url 'logs:search_patterns_list' %}">Поисковые паттерны</a>
                <a class="col-4 btn btn-outline-light mx-1" href="{% url 'logs:one_time_scans_list' %}">Одноразовые сканирования</a>
            {% endif %}
        </div>
        <div class="col-3 d-flex justify-content-end">
            
            {% if request.user.role in 'ADMIN,SPECIALIST' %}
                <a class="col-1 btn btn-outline-light mx-1" href="{% url 'logs:generate_test_anomalous_event' %}">▲</a>
            {% endif %}

            {% if request.user.role == 'ADMIN' %}
                <a class="col-sm-5 col-xl-6 btn btn-outline-light mx-1" href="{% url 'users:users_list' %}">Пользователи системы</a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <form class="col-5" action="{% url 'users:user_logout' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12">
                            <button class="btn btn-outline-light w-100" type="submit">Выйти из аккаунта</button>
                        </div>
                    </div>
                </form>
            {% else %}
                <a class="col-6 btn btn-outline-light mx-1" href="{% url 'users:user_login' %}">Войти в аккаунт</a>
            {% endif %}

        </div>
    </div>
</div>

web/templates/includes/paginator.html
{% if page.has_other_pages %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Самые новые</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">Новее</a>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Старее</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.paginator.num_pages }}">Самые старые</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

web/templates/includes/websocket-notificator.html
{% load static %}
<audio id="notificationSound" preload="auto" src="{% static 'audio/notification.mp3' %}"></audio>
<div id="notificationContainer" class="position-fixed bottom-0 end-0 p-3" style="display: none;">
    <div class="card" id="notificationWrapper" style="max-width: 470px;">
        <div class="card-header bg-danger text-dark d-flex justify-content-between">
            <strong>Уведомление</strong>
            <button type="button" class="btn-close"></button>
        </div>
        <div class="card-body text-dark">
            <!-- websocket message  -->
        </div>
    </div>
</div>
<script>
    socket_url = 'ws://' + window.location.hostname + ":" + window.location.port + '/ws'
    const socket = new WebSocket(socket_url);
    const notificationSound = document.getElementById('notificationSound');

    socket.onmessage = function (event) {
        try {
            var data = JSON.parse(event.data);

            $('#notificationContainer').show();
            notificationSound.play();
            setTimeout(function () {
                $('#notificationContainer').hide();
            }, 10000);
            $('#notificationWrapper .card-body').text(
                "[" + data.id + "] В лог-файле " + data.log_file.name + " произошло новое событие: " + data.text
            );
        } catch (e) {
            console.log('Error:', e.message);
        }
    };

    $('.btn-close').click(function () {
        $('#notificationContainer').hide();
    });
</script>