web/logs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.decorators import specialist_required
from logs.views import (
    AnomalousEventDeleteView,
    AnomalousEventListView,
    GenerateTestAnomalousEventView,
    LogFileAddView,
    LogFileDeleteView,
    LogFileEditView,
    LogFileListView,
    LogTypeAddView,
    LogTypeDeleteView,
    LogTypeEditView,
    LogTypeListView,
    MainPageView,
    OneTimeScanAddView,
    OneTimeScanAnomalousEventListView,
    OneTimeScanDeleteView,
    OneTimeScanListView,
    SearchPatternAddView,
    SearchPatternDeleteView,
    SearchPatternEditView,
    SearchPatternListView,
)


app_name = "logs"

urlpatterns = [
    path(
        "anomalous-events/",
        login_required(AnomalousEventListView.as_view()),
        name="anomalous_events_list",
    ),
    path(
        "anomalous-events/<int:anomalous_event_id>/delete",
        specialist_required(AnomalousEventDeleteView.as_view()),
        name="anomalous_event_delete",
    ),
    path(
        "log-files/", login_required(LogFileListView.as_view()), name="log_files_list"
    ),
    path(
        "log-files/add/",
        specialist_required(LogFileAddView.as_view()),
        name="log_file_add",
    ),
    path(
        "log-files/<int:log_file_id>/edit/",
        specialist_required(LogFileEditView.as_view()),
        name="log_file_edit",
    ),
    path(
        "log-files/<int:log_file_id>/delete/",
        specialist_required(LogFileDeleteView.as_view()),
        name="log_file_delete",
    ),
    path(
        "log-types/", login_required(LogTypeListView.as_view()), name="log_types_list"
    ),
    path(
        "log-types/add/",
        specialist_required(LogTypeAddView.as_view()),
        name="log_type_add",
    ),
    path(
        "log-types/<int:log_type_id>/edit/",
        specialist_required(LogTypeEditView.as_view()),
        name="log_type_edit",
    ),
    path(
        "log-types/<int:log_type_id>/delete/",
        specialist_required(LogTypeDeleteView.as_view()),
        name="log_type_delete",
    ),
    path(
        "search-patterns/",
        login_required(SearchPatternListView.as_view()),
        name="search_patterns_list",
    ),
    path(
        "search-patterns/add/",
        specialist_required(SearchPatternAddView.as_view()),
        name="search_pattern_add",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/edit/",
        specialist_required(SearchPatternEditView.as_view()),
        name="search_pattern_edit",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/delete/",
        specialist_required(SearchPatternDeleteView.as_view()),
        name="search_pattern_delete",
    ),
    path(
        "one-time-scans/",
        login_required(OneTimeScanListView.as_view()),
        name="one_time_scans_list",
    ),
    path(
        "one-time-scans/add/",
        specialist_required(OneTimeScanAddView.as_view()),
        name="one_time_scan_add",
    ),
    path(
        "one-time-scans/<int:log_file_id>/delete/",
        specialist_required(OneTimeScanDeleteView.as_view()),
        name="one_time_scan_delete",
    ),
    path(
        "one-time-scans/<int:log_file_id>/anomalous-events/",
        login_required(OneTimeScanAnomalousEventListView.as_view()),
        name="one_time_scan_anomalous_events_list",
    ),
    path(
        "generate-test-anomalous-event/",
        login_required(GenerateTestAnomalousEventView.as_view()),
        name="generate_test_anomalous_event",
    ),
    path("", login_required(MainPageView.as_view()), name="main_page"),
]

web/main/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path("users/", include("users.urls")),
    path("logs/", include("logs.urls")),
    path("", RedirectView.as_view(url="logs/")),
]

web/logs/models.py
from enum import Enum

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class SearchPatternTypeChoices(Enum):
    SIMPLE = "По полному вхождению"
    REGEX = "Регулярное выражение"
    COEFFICIENT = "Словарный коэффициент вхождения"

    @classmethod
    def choices(cls):
        return tuple((role.name, role.value) for role in cls)

    @classmethod
    def choices_with_none(cls):
        return ((None, "Любой"),) + cls.choices()


class NotificationType(models.Model):
    description = models.CharField(
        max_length=64, verbose_name="Описание", null=False, blank=False
    )
    method = models.CharField(
        max_length=64,
        verbose_name="Метод оповещения",
        null=False,
        blank=False,
        unique=True,
    )

    class Meta:
        verbose_name_plural = "Типы оповещений"
        verbose_name = "Тип оповещения"
        ordering = ("id",)

    def __str__(self):
        return self.description


class SearchPattern(models.Model):
    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name="Краткое понятное название или описание",
    )
    pattern = models.CharField(verbose_name="Поисковый паттерн", max_length=4096)
    search_type = models.CharField(
        verbose_name="Тип поиска",
        max_length=255,
        choices=SearchPatternTypeChoices.choices(),
        null=False,
        blank=False,
    )
    notification_types = models.ManyToManyField(
        NotificationType,
        through="SearchPatternNotificationType",
        verbose_name="Типы оповещений",
        related_name="search_patterns",
    )
    counter = models.BooleanField(verbose_name="Повторяющееся событие", default=False)
    # only for coefficient search type
    coefficient = models.FloatField(
        verbose_name="Словарный коэффициент вхождения",
        null=True,
        default=None,
        validators=[MinValueValidator(0), MaxValueValidator(1)],
    )
    # only for count events if counter field is True
    count_of_events = models.IntegerField(
        verbose_name="Количество событий до оповещения", null=True, default=0
    )
    period_of_events = models.TimeField(
        verbose_name="Период для подсчёта количества событий до оповещения",
        null=True,
        default=None,
    )

    class Meta:
        verbose_name_plural = "Поисковые паттерны"
        verbose_name = "Поисковый паттерн"
        ordering = ("id",)

    def __str__(self):
        return self.name


class SearchPatternNotificationType(models.Model):
    search_pattern = models.ForeignKey(
        SearchPattern,
        on_delete=models.SET_NULL,
        null=True,
        related_name="search_pattern_notification_types",
        verbose_name="Поисковый паттерн типа оповещения",
    )
    notification_type = models.ForeignKey(
        NotificationType,
        on_delete=models.SET_NULL,
        null=True,
        related_name="notification_type_search_patterns",
        verbose_name="Тип оповещения поискового паттерна",
    )

    class Meta:
        verbose_name_plural = "Связи поисковых паттернов и типов оповещений"
        verbose_name = "Связь поискового паттерна и типа оповещения"
        ordering = ("id",)

    def __str__(self):
        return f"Поисковый паттерн '{self.search_pattern}' использует тип оповещения '{self.notification_type}'"


class LogType(models.Model):
    name = models.CharField(
        verbose_name="Краткое понятное название или описание", max_length=255
    )
    search_patterns = models.ManyToManyField(
        SearchPattern,
        through="LogTypeSearchPattern",
        related_name="log_types",
        verbose_name="Подвязанные поисковые паттерны",
    )

    class Meta:
        verbose_name_plural = "Типы протоколов / ПО лог-файла"
        verbose_name = "Тип протокола / ПО лог-файла"
        ordering = ("id",)

    def __str__(self):
        return self.name


class LogTypeSearchPattern(models.Model):
    log_type = models.ForeignKey(
        LogType,
        on_delete=models.SET_NULL,
        null=True,
        related_name="log_type_search_patterns",
    )
    search_pattern = models.ForeignKey(
        SearchPattern,
        on_delete=models.SET_NULL,
        null=True,
        related_name="search_pattern_log_types",
    )

    class Meta:
        verbose_name_plural = "Связи типов протокола / ПО и поисковых паттернов"
        verbose_name = "Связь типа протокола / ПО и поискового паттерна"
        ordering = ("id",)

    def __str__(self):
        return f"Тип протокола / ПО '{self.log_type}' использует поисковый паттерн '{self.search_pattern}'"


class LogFile(models.Model):
    name = models.CharField(
        verbose_name="Краткое понятное название или описание", max_length=255
    )
    path = models.CharField(verbose_name="Физический путь до файла", max_length=255)
    type = models.ForeignKey(
        LogType,
        on_delete=models.SET_NULL,
        null=True,
        related_name="log_files",
    )
    one_time_scan = models.BooleanField(
        verbose_name="Одноразовое сканирование", default=False
    )
    one_time_scan_is_done = models.BooleanField(
        verbose_name="Одноразовое сканирование заверешно", default=False
    )
    last_positions = models.IntegerField(
        verbose_name="Последняя позиция при чтении", default=0
    )

    class Meta:
        verbose_name_plural = "Лог-файлы"
        verbose_name = "Лог-файл"
        ordering = ("id",)

    def __str__(self):
        return self.name


class AnomalousEvent(models.Model):
    text = models.CharField(verbose_name="Текст", max_length=2048)
    fact_datetime = models.DateTimeField(
        verbose_name="Фактическое дата и время", null=True, blank=True
    )
    detected_datetime = models.DateTimeField(
        verbose_name="Дата и время обнаружения", auto_now_add=True
    )
    log_file = models.ForeignKey(
        LogFile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="anomalous_events",
    )
    count_of_events = models.IntegerField(
        verbose_name="Количество событий в рамках периода", null=True, default=0
    )
    detected_search_pattern = models.ForeignKey(
        SearchPattern,
        on_delete=models.SET_NULL,
        null=True,
        related_name="anomalous_events",
    )

    class Meta:
        verbose_name_plural = "Аномальные события лог-файла"
        verbose_name = "Аномальное событие лог-файла"
        ordering = ("-id",)

    def __str__(self):
        return self.text

web/templates/logs/search-patterns/search-pattern-form.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}
    Изменение поискового паттерна
{% else %}
    Добавление поискового паттерна
{% endif %}
{% endblock %}

{% block header %} {% include 'includes/header.html' %} {% endblock %}
{% block content %}

<div class="min-vh-100 d-flex justify-content-center align-items-center">
    <form class="g-3 w-25" action="
        {% if is_edit %} 
            {% url 'logs:search_pattern_edit' search_pattern_id=search_pattern_id %}
        {% else %}
            {% url 'logs:search_pattern_add' %}
        {% endif %}" method="post">

        {% csrf_token %}

        {% for field in form %}
            <div class="col-12 mb-2">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div>{{ field }}</div>
            </div>
        {% endfor %}

        <div class="col-12 text-center">
            <button type="submit" class="btn btn-outline-light col-12 mt-2">
                {% if is_edit %}
                    Измененить поисковый паттерн
                {% else %}
                    Добавить поисковый паттерн
                {% endif %}
            </button>
        </div>
    </form>
</div>
<script>
    $("label[for='id_notification_types_0'] input").attr("disabled", true);

    var coefficientHidden = !($('#id_search_type').find(":selected").val() == "COEFFICIENT");
    var countOfEventsHidden = !$('#id_counter').is(':checked');
    var periodOfEventsHidden = !$('#id_counter').is(':checked');
    $("label[for='id_coefficient']").parent().attr("hidden", coefficientHidden);    
    $("label[for='id_count_of_events']").parent().attr("hidden", countOfEventsHidden);    
    $("label[for='id_period_of_events']").parent().attr("hidden", periodOfEventsHidden);    

    function changeHiddenCoefficient () {
        var selectedOption = $('#id_search_type').find(":selected").val();
        if (selectedOption == "COEFFICIENT"){
            coefficientHidden = false;
        } else {
            $('#id_coefficient').val('');
            coefficientHidden = true;
        }
        $("label[for='id_coefficient']").parent().attr("hidden", coefficientHidden);       
    }

    function changeHiddenCounter () {
        countOfEventsHidden = !countOfEventsHidden;
        periodOfEventsHidden = !periodOfEventsHidden;
        if (countOfEventsHidden & periodOfEventsHidden) {
            $('#id_count_of_events').val('');
            $('#id_period_of_events').val('');
        }
        $("label[for='id_count_of_events']").parent().attr("hidden", countOfEventsHidden);    
        $("label[for='id_period_of_events']").parent().attr("hidden", periodOfEventsHidden);    
    }

    $("#id_search_type").on("change", changeHiddenCoefficient);
    $("#id_counter").on("change", changeHiddenCounter);

</script>
{% endblock %}

web/templates/logs/search-patterns/search-patterns-list.html
{% extends 'base.html' %}
{% block title %} Список поисковых паттернов {% endblock %}
{% block header %} {% include 'includes/header.html' %} {% endblock %}
{% block content %}
<div class="mx-5 mt-5 text-center">
    <h2 class="mb-4">Список добавленных поисковых паттернов</h2>

    <form class="col-12 mb-3 g-3" action="{% url 'logs:search_patterns_list' %}" method="post">
        {% csrf_token %}

        <div class="row">
            {% for field in form %}
                <div class="col-3 mb-2">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div>{{ field }}</div>
                </div>
            {% endfor %}
        </div>

        <div class="d-flex justify-content-center text-center">
            <button type="submit" class="btn btn-outline-light col-2 mt-2">
                Поиск
            </button>
        </div>

    </form>

    {% if request.user.role in 'ADMIN,SPECIALIST' %}
        <a class="col-4 btn btn-outline-light mx-1 mb-4" href="{% url 'logs:search_pattern_add' %}">Добавить поисковый паттерн</a>
    {% endif %}
    <table class="table table-striped table-dark table-bordered border-white align-middle">
        <thead class="align-middle">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Описание</th>
                <th scope="col">Паттерн</th>
                <th scope="col">Тип поиска</th>
                <th scope="col">Типы оповещений</th>
                <th scope="col">Действие</th>
            </tr>
        </thead>
        <tbody>
            {% for search_pattern in search_patterns %}
            <tr>
                <th scope="row" id="{{ search_pattern.id }}">{{ search_pattern.id }}</th>
                <td>{{ search_pattern.name }}</td>
                <td class="col-6">{{ search_pattern.pattern }}</td>
                <td>{{ search_pattern.get_search_type_display }}</td>
                <td>
                    {% for notification_type in search_pattern.notification_types.all %}
                        <a class="col-10 btn btn-sm btn-outline-light m-1" href="{% url 'logs:search_pattern_edit' search_pattern_id=search_pattern.id %}">{{ notification_type }}</a>
                    {% endfor %}
                </td>
                <td>
                    {% if request.user.role in 'ADMIN,SPECIALIST' %}
                        <a class="col-7 btn btn-sm btn-outline-light m-1" href="{% url 'logs:search_pattern_edit' search_pattern_id=search_pattern.id %}">Изменить</a>
                        <a class="col-7 btn btn-sm btn-outline-light m-1" href="{% url 'logs:search_pattern_delete' search_pattern_id=search_pattern.id %}">Удалить</a>
                    {% else %}
                        —
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'includes/anchor_finder.html' %}
{% endblock %}