web/logs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.decorators import specialist_required
from logs.views import (
    AnomalousEventDeleteView,
    AnomalousEventListView,
    GenerateTestAnomalousEventView,
    LogFileAddView,
    LogFileDeleteView,
    LogFileEditView,
    LogFileListView,
    LogTypeAddView,
    LogTypeDeleteView,
    LogTypeEditView,
    LogTypeListView,
    MainPageView,
    OneTimeScanAddView,
    OneTimeScanAnomalousEventListView,
    OneTimeScanDeleteView,
    OneTimeScanListView,
    SearchPatternAddView,
    SearchPatternDeleteView,
    SearchPatternEditView,
    SearchPatternListView,
)


app_name = "logs"

urlpatterns = [
    path(
        "anomalous-events/",
        login_required(AnomalousEventListView.as_view()),
        name="anomalous_events_list",
    ),
    path(
        "anomalous-events/<int:anomalous_event_id>/delete",
        specialist_required(AnomalousEventDeleteView.as_view()),
        name="anomalous_event_delete",
    ),
    path(
        "log-files/", login_required(LogFileListView.as_view()), name="log_files_list"
    ),
    path(
        "log-files/add/",
        specialist_required(LogFileAddView.as_view()),
        name="log_file_add",
    ),
    path(
        "log-files/<int:log_file_id>/edit/",
        specialist_required(LogFileEditView.as_view()),
        name="log_file_edit",
    ),
    path(
        "log-files/<int:log_file_id>/delete/",
        specialist_required(LogFileDeleteView.as_view()),
        name="log_file_delete",
    ),
    path(
        "log-types/", login_required(LogTypeListView.as_view()), name="log_types_list"
    ),
    path(
        "log-types/add/",
        specialist_required(LogTypeAddView.as_view()),
        name="log_type_add",
    ),
    path(
        "log-types/<int:log_type_id>/edit/",
        specialist_required(LogTypeEditView.as_view()),
        name="log_type_edit",
    ),
    path(
        "log-types/<int:log_type_id>/delete/",
        specialist_required(LogTypeDeleteView.as_view()),
        name="log_type_delete",
    ),
    path(
        "search-patterns/",
        login_required(SearchPatternListView.as_view()),
        name="search_patterns_list",
    ),
    path(
        "search-patterns/add/",
        specialist_required(SearchPatternAddView.as_view()),
        name="search_pattern_add",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/edit/",
        specialist_required(SearchPatternEditView.as_view()),
        name="search_pattern_edit",
    ),
    path(
        "search-patterns/<int:search_pattern_id>/delete/",
        specialist_required(SearchPatternDeleteView.as_view()),
        name="search_pattern_delete",
    ),
    path(
        "one-time-scans/",
        login_required(OneTimeScanListView.as_view()),
        name="one_time_scans_list",
    ),
    path(
        "one-time-scans/add/",
        specialist_required(OneTimeScanAddView.as_view()),
        name="one_time_scan_add",
    ),
    path(
        "one-time-scans/<int:log_file_id>/delete/",
        specialist_required(OneTimeScanDeleteView.as_view()),
        name="one_time_scan_delete",
    ),
    path(
        "one-time-scans/<int:log_file_id>/anomalous-events/",
        login_required(OneTimeScanAnomalousEventListView.as_view()),
        name="one_time_scan_anomalous_events_list",
    ),
    path(
        "generate-test-anomalous-event/",
        login_required(GenerateTestAnomalousEventView.as_view()),
        name="generate_test_anomalous_event",
    ),
    path("", login_required(MainPageView.as_view()), name="main_page"),
]

web/main/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path("users/", include("users.urls")),
    path("logs/", include("logs.urls")),
    path("", RedirectView.as_view(url="logs/")),
]

web/logs/views.py
import datetime
import json
from random import randint
from zoneinfo import ZoneInfo

from qsstats import QuerySetStats

from django import views
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

from core.utils import notificate_selector
from logs.forms import (
    AnomalousEventMainPageSearchForm,
    AnomalousEventSearchForm,
    LogFileForm,
    LogFileSearchForm,
    LogTypeForm,
    LogTypeSearchForm,
    OneTimeScanAnomalousEventSearchForm,
    SearchPatternForm,
    SearchPatternSearchForm,
)
from logs.models import (
    AnomalousEvent,
    LogFile,
    LogType,
    NotificationType,
    SearchPattern,
)
from logs.tasks import read_log_file_task


class GenerateTestAnomalousEventView(views.View):
    def get(self, request, *args, **kwargs):
        log_files = LogFile.objects.filter(one_time_scan=False)
        if log_files:
            log_file = log_files[randint(0, len(log_files) - 1)]
            texts = [
                "Тестовая строка 1",
                "Тестовая строка 2",
                "Тестовая строка 3",
                "Тестовая строка 4",
            ]
            text = texts[randint(0, len(texts) - 1)]
            search_patterns = log_file.type.search_patterns.all()
            anomalous_event = AnomalousEvent.objects.create(
                text=text,
                count_of_events=None,
                log_file=log_file,
                detected_search_pattern=search_patterns[
                    randint(0, len(search_patterns) - 1)
                ],
            )
            notification_types = (
                anomalous_event.detected_search_pattern.notification_types.all()
            )
            notificate_selector(anomalous_event, notification_types)
            print(anomalous_event)
        return render(
            request,
            template_name="success.html",
            context={"message": "Вы успешно сгенерировали аномальное событие"},
        )


class MainPageView(views.View):
    def get(self, request, *args, **kwargs):
        form = AnomalousEventMainPageSearchForm()
        start_datetime = datetime.datetime.now(
            tz=ZoneInfo(key="Asia/Yekaterinburg")
        ).replace(hour=0, minute=0, second=0, microsecond=0)
        end_datetime = start_datetime + datetime.timedelta(days=1)
        anomalous_events = AnomalousEvent.objects.filter(
            detected_datetime__gt=start_datetime,
            detected_datetime__lt=end_datetime,
            log_file__one_time_scan=False,
            count_of_events=None,
        )
        qsstats = QuerySetStats(anomalous_events, date_field="detected_datetime")
        logs_metrics = qsstats.time_series(
            start_datetime, end_datetime, interval="minutes"
        )
        logs_metrics = list(
            filter(lambda x: x[1] > 0 or x[0].minute % 30 == 0, logs_metrics)
        )
        logs_metrics = [[str(i[0]), i[1]] for i in logs_metrics]
        return render(
            request,
            template_name="logs/index.html",
            context={
                "form": form,
                "logs_metrics": json.dumps(logs_metrics),
                "start_datetime": start_datetime,
                "end_datetime": end_datetime,
                "anomalous_events": anomalous_events[:6],
            },
        )

    def post(self, request, *args, **kwargs):
        form = AnomalousEventMainPageSearchForm(request.POST)
        if not form.is_valid():
            return self.get(self, request, *args, **kwargs)
        text, start_datetime, end_datetime, log_file, log_type, search_pattern = (
            form.cleaned_data.values()
        )
        anomalous_events = AnomalousEvent.objects.filter(
            detected_datetime__gt=start_datetime,
            detected_datetime__lt=end_datetime,
            log_file__one_time_scan=False,
            count_of_events=None,
        )
        if text:
            anomalous_events = anomalous_events.filter(text__icontains=text)
        if log_file:
            anomalous_events = anomalous_events.filter(log_file=log_file)
        if log_type:
            anomalous_events = anomalous_events.filter(log_file__type=log_type)
        if search_pattern:
            log_types = search_pattern.log_types.all()
            if log_types:
                anomalous_events = anomalous_events.filter(log_file__type__in=log_types)
        qsstats = QuerySetStats(anomalous_events, date_field="detected_datetime")
        logs_metrics = qsstats.time_series(
            start_datetime, end_datetime, interval="minutes"
        )
        logs_metrics = list(
            filter(lambda x: x[1] > 0 or x[0].minute % 30 == 0, logs_metrics)
        )
        logs_metrics = [[str(i[0]), i[1]] for i in logs_metrics]
        return render(
            request,
            template_name="logs/index.html",
            context={
                "form": form,
                "logs_metrics": json.dumps(logs_metrics),
                "start_datetime": start_datetime,
                "end_datetime": end_datetime,
                "anomalous_events": anomalous_events[:6],
            },
        )


# Anomalous Event Views


class AnomalousEventListView(views.View):
    def get(self, request, *args, **kwargs):
        anomalous_events = AnomalousEvent.objects.filter(
            log_file__one_time_scan=False, count_of_events=None
        )
        paginator = Paginator(anomalous_events, 50)
        page = paginator.get_page(self.request.GET.get("page"))
        form = AnomalousEventSearchForm()
        return render(
            request,
            template_name="logs/anomalous-events/anomalous-events-list.html",
            context={"form": form, "page": page},
        )

    def post(self, request, *args, **kwargs):
        form = AnomalousEventSearchForm(request.POST)
        if not form.is_valid():
            return self.get(self, request, *args, **kwargs)
        text, start_datetime, end_datetime, log_file, log_type, search_pattern = (
            form.cleaned_data.values()
        )
        anomalous_events = AnomalousEvent.objects.filter(
            log_file__one_time_scan=False, count_of_events=None
        )
        if start_datetime:
            anomalous_events = anomalous_events.filter(
                detected_datetime__gt=start_datetime
            )
        if end_datetime:
            anomalous_events = anomalous_events.filter(
                detected_datetime__lt=end_datetime
            )
        if text:
            anomalous_events = anomalous_events.filter(text__icontains=text)
        if log_file:
            anomalous_events = anomalous_events.filter(log_file=log_file)
        if log_type:
            anomalous_events = anomalous_events.filter(log_file__type=log_type)
        if search_pattern:
            anomalous_events = anomalous_events.filter(
                log_file__type__search_patterns=search_pattern
            )
        paginator = Paginator(anomalous_events, 50)
        page = paginator.get_page(self.request.GET.get("page"))
        return render(
            request,
            template_name="logs/anomalous-events/anomalous-events-list.html",
            context={"form": form, "page": page},
        )


class AnomalousEventDeleteView(views.View):
    def get(self, request, anomalous_event_id, *args, **kwargs):
        anomalous_event = get_object_or_404(AnomalousEvent, id=anomalous_event_id)
        anomalous_event.delete()
        return render(
            request,
            template_name="success.html",
            context={"message": "Вы успешно удалили аномальное событие"},
        )


# Log File Views


class LogFileListView(views.View):
    def get(self, request, *args, **kwargs):
        log_files = LogFile.objects.filter(one_time_scan=False)
        form = LogFileSearchForm()
        return render(
            request,
            template_name="logs/log-files/log-files-list.html",
            context={"log_files": log_files, "form": form},
        )

    def post(self, request, *args, **kwargs):
        form = LogFileSearchForm(request.POST)
        if not form.is_valid():
            return self.get(self, request, *args, **kwargs)
        log_files = LogFile.objects.filter(one_time_scan=False)
        name, path, log_type, search_pattern = form.cleaned_data.values()
        print(form.cleaned_data)
        if name:
            log_files = log_files.filter(name__icontains=name)
        if path:
            log_files = log_files.filter(path__icontains=path)
        if log_type:
            log_files = log_files.filter(type=log_type)
        if search_pattern:
            log_files = log_files.filter(type__search_patterns=search_pattern)
        return render(
            request,
            template_name="logs/log-files/log-files-list.html",
            context={"log_files": log_files, "form": form},
        )


class LogFileAddView(views.View):
    def get(self, request, *args, **kwargs):
        form = LogFileForm()
        return render(
            request,
            template_name="logs/log-files/log-file-form.html",
            context={"form": form},
        )

    def post(self, request, *args, **kwargs):
        form = LogFileForm(request.POST)
        if not form.is_valid():
            return render(
                request,
                template_name="logs/log-files/log-file-form.html",
                context={"form": form},
            )
        LogFile.objects.create(**form.cleaned_data, one_time_scan=False)
        return render(
            request,
            template_name="success.html",
            context={"message": "Вы успешно добавили лог-файл"},
        )


class LogFileEditView(views.View):
    def get(self, request, log_file_id, *args, **kwargs):
        log_file = get_object_or_404(LogFile, id=log_file_id)
        form = LogFileForm(instance=log_file)
        return render(
            request,
            template_name="logs/log-files/log-file-form.html",

web/templates/logs/one-time-scans/one-time-scan-anomalous-events-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Аномальные события {% endblock %}
{% block header %} {% include 'includes/header.html' %} {% endblock %}
{% block content %}
<div class="mx-5 mt-5 text-center">
    {% if page.0.log_file.one_time_scan_is_done %}
        <h2 class="mb-3">Список аномальных событий в лог-файле {{ page.0.log_file.name }} (сканирование заверешно)</h2>
    {% else %}
        <h2 class="mb-3">Список аномальных событий в лог-файле {{ page.0.log_file.name }} (сканирование в процессе)</h2>
    {% endif %}
        <div class="d-flex justify-content-center">
        <form class="col-6 mb-3 g-3" action="{% url 'logs:one_time_scan_anomalous_events_list' log_file_id=log_file_id%}" method="post">
            {% csrf_token %}
        
            <div class="row">
                {% for field in form %}
                    <div class="col-6 mb-2">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div>{{ field }}</div>
                    </div>
                {% endfor %}
            </div>

            <div class="d-flex justify-content-center text-center">
                <button type="submit" class="btn btn-outline-light col-12 mt-2">
                    Поиск
                </button>
            </div>
        </form>
    </div>

    {% include 'includes/paginator.html' %}
    <table class="table table-striped table-dark table-bordered border-white align-middle col-12">
        <thead class="align-middle">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Событие</th>
                <th scope="col">Фактическое дата и время</th>
                <th scope="col">Дата и время детекции</th>
                <th scope="col">Поисковый паттерн</th>
                <th scope="col">Действие</th>
            </tr>
        </thead>
        <tbody>
            {% for anomalous_event in page %}
            <tr>
                <th scope="row" id="{{ anomalous_event.id }}">{{ anomalous_event.id }}</th>
                <td>{{ anomalous_event.text }}</td>
                <td>
                    {% if anomalous_event.fact_datetime %}
                        {{ anomalous_event.fact_datetime }}
                    {% else %}
                        —
                    {% endif %}
                </td>
                <td>{{ anomalous_event.detected_datetime }}</td>
                <td>
                    <a class="col-10 btn btn-sm btn-outline-light mx-1" href="{% url 'logs:search_patterns_list'%}#{{ anomalous_event.detected_search_pattern.id }}">{{ anomalous_event.detected_search_pattern }}</a>
                </td>
                <td>
                    <a class="col-10 btn btn-sm btn-outline-light m-1" href="{% url 'logs:anomalous_event_delete' anomalous_event_id=anomalous_event.id %}">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'includes/paginator.html' %}
    
</div>
{% include 'includes/anchor_finder.html' %}
{% endblock %}
{% block websocket_notificator %}
    <audio id="notificationSound" preload="auto" src="{% static 'audio/notification.mp3' %}"></audio>
    <div id="notificationContainer" class="position-fixed bottom-0 end-0 p-3" style="display: none;">
        <div class="card" id="notificationWrapper" style="max-width: 470px;">
            <div class="card-header bg-danger text-dark d-flex justify-content-between">
                <strong>Уведомление</strong>
                <button type="button" class="btn-close"></button>
            </div>
            <div class="card-body text-dark">
                <!-- websocket message  -->
            </div>
        </div>
    </div>
    <script>
        socket_url = 'ws://' + window.location.hostname + ":" + window.location.port + '/ws'
        const socket = new WebSocket(socket_url);
        const notificationSound = document.getElementById('notificationSound');

        socket.onmessage = function (event) {
            try {
                var data = JSON.parse(event.data);

                $('#notificationContainer').show();
                notificationSound.play();
                setTimeout(function () {
                    $('#notificationContainer').hide();
                }, 10000);
                $('#notificationWrapper .card-body').text(
                    "[" + data.id + "] В лог-файле " + data.log_file.name + " произошло новое событие: " + data.text
                );

                var tableRows = $('.table tbody tr');
                
                var timeOptions = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' };

                if (data.fact_datetime == 'None') {
                    data.fact_datetime = '—';
                }
                else {
                    data.fact_datetime = new Date(data.fact_datetime).toLocaleDateString('ru-RU', timeOptions).replace('в', '');
                }
                
                data.detected_datetime = new Date(data.detected_datetime).toLocaleDateString('ru-RU', timeOptions).replace('в', '');

                $('.table tbody').prepend('<tr>');
                $('.table tbody tr').first().append('<th scope="row" id="' + data.id + '">' + data.id + '</th>');
                $('.table tbody tr').first().append('<td>' + data.text + '</td>');
                $('.table tbody tr').first().append('<td>' + data.fact_datetime + '</td>');
                $('.table tbody tr').first().append('<td>' + data.detected_datetime + '</td>');
                $('.table tbody tr').first().append("<td><a class='col-10 btn btn-sm btn-outline-light mx-1' href='{% url 'logs:log_files_list'%}#" + data.log_file.id + "'>" + data.log_file.name + "</a></td>");
                $('.table tbody tr').first().append("<td><a class='col-7 btn btn-sm btn-outline-light m-1' href='/logs/anomalous-events/" + data.id + "/delete'>Удалить</a></td>");
                $('.table tbody').prepend('</tr>');
            } catch (e) {
                console.log('Error:', e.message);
            }
        };

        $('.btn-close').click(function () {
            $('#notificationContainer').hide();
        });
    </script>
{% endblock %}

web/templates/logs/one-time-scans/one-time-scan-form.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}
    Изменение лог-файла
{% else %}
    Добавление лог-файла
{% endif %}
{% endblock %}

{% block header %} {% include 'includes/header.html' %} {% endblock %}
{% block content %}

<div class="min-vh-100 d-flex justify-content-center align-items-center">
    <form class="g-3 w-25" action="{% url 'logs:one_time_scan_add' %}" method="post">

        {% csrf_token %}

        {% for field in form %}
        <div class="col-12 mb-2">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div>{{ field }}</div>
        </div>
        {% endfor %}

        <div class="col-12 text-center">
            <button type="submit" class="btn btn-outline-light col-12 mt-2">
                {% if is_edit %}
                    Измененить лог-файл
                {% else %}
                    Добавить лог-файл
                {% endif %}
            </button>
        </div>
    </form>
</div>

{% endblock %}

web/templates/logs/one-time-scans/one-time-scans-list.html
{% extends 'base.html' %}
{% block title %} Список лог-файлов {% endblock %}
{% block header %} {% include 'includes/header.html' %} {% endblock %}
{% block content %}
<div class="mx-5 mt-5 text-center">
    <h2 class="mb-4">Список добавленных лог-файлов для одноразового сканирования</h2>
    {% if request.user.role in 'ADMIN,SPECIALIST' %}
        <a class="col-4 btn btn-outline-light mx-1 mb-4" href="{% url 'logs:one_time_scan_add' %}">Добавить лог-файл</a>
    {% endif %}
    <table class="table table-striped table-dark table-bordered border-white align-middle">
        <thead class="align-middle">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Описание</th>
                <th scope="col">Путь</th>
                <th scope="col">Тип протокола / ПО</th>
                <th scope="col">Действие</th>
            </tr>
        </thead>
        <tbody>
            {% for log_file in log_files %}
            <tr>
                <th scope="row" id="{{ log_file.id }}">{{ log_file.id }}</th>
                <td>{{ log_file.name }}</td>
                <td>{{ log_file.path }}</td>
                <td>
                    {% if log_file.type %}
                        <a class="col-10 btn btn-sm btn-outline-light mx-1" href="{% url 'logs:log_types_list'%}#{{ log_file.type.id }}">{{ log_file.type }}</a>
                    {% else %}
                        —
                    {% endif %}
                </td>
                <td>
                    {% if request.user.role in 'ADMIN,SPECIALIST' %}
                        {% if log_file.one_time_scan_is_done %}
                            <a class="col-7 btn btn-sm btn-outline-light m-1" href="{% url 'logs:one_time_scan_anomalous_events_list' log_file_id=log_file.id %}">Результаты</a>
                        {% else %}
                            <a class="col-7 btn btn-sm btn-outline-light m-1" href="{% url 'logs:one_time_scan_anomalous_events_list' log_file_id=log_file.id %}">Сканирование в процессе</a>
                        {% endif %}
                        <a class="col-7 btn btn-sm btn-outline-light m-1" href="{% url 'logs:one_time_scan_delete' log_file_id=log_file.id %}">Удалить</a>
                    {% else %}
                        —
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'includes/anchor_finder.html' %}
{% endblock %}